# name: pydoc_integration
# run-name: ${{ github.actor }} has made changes affecting the documentation
# on: [push]
# jobs:
#   build:
#     name: "Update the documentation"
#     runs-on: ubuntu-latest
#     steps:
#         - name: Checkout the repository
#           uses: actions/checkout@main
#         - name: Install PyDoc-Markdown
#           run: |
#             sudo apt-get update
#             sudo apt-get install python3.10
#             sudo apt install pipx
#             pipx install pydoc-markdown
#         - name: Update README.md  
#           run: |
#             git config --global user.name ${{ github.triggering_actor }}
#             pydoc-markdown -m amod -I $(pwd) > README.md
#             git add README.md
#             git commit -m "Update README.md"
#             git push

#typing
#multiple modules
#vanilla pydoc
#documentation branch instead of main
#gh-pages integration

name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ..
        requirements_path: ../requirements.txt
        cache: true
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}