name: pydoc_integration
run-name: ${{ github.actor }} has made changes affecting the documentation
on: [push]
jobs:
  build:
    name: "Update the documentation"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@main
        - name: Install Python
          run: |
            sudo apt-get update
            sudo apt-get install python3.10
            sudo apt install pipx
            pipx install pydoc-markdown
        
        - name: Update README.md  
          run: |
            pwd
            ls -a
            pydoc-markdown -m code -I $(pwd) > README.md
            git push