name: pydoc_integration
run-name: ${{ github.actor }} has updated the documentation
on: [push]
jobs:
  build:
    name: "Update the documentation"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@main
          
        - name: Update README.md  
          run: |
            sed -i 's/<reponame>/'${{ github.event.repository.name }}'/' README.md
            git config user.email "sahej3526@gmail.com"
            git config user.name "stsingh"
            git commit -am "Automated report"
            git push