name: pydoc_integration
run-name: ${{ github.actor }} has updated the documentation
on: [push]
jobs:
  build:
    name: "Update the documentation"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@main
        - name: Install Python
          run: |
            sudo apt-get update
            sudo apt-get install python3.8
            python3 -m pip install --upgrade pip
            pip install pydoc-markdown
        
        - name: Update README.md  
          run: |
            pydoc -w README.md
            git config user.email "sahej3526@gmail.com"
            git config user.name "stsingh"
            git commit -am "Automated report"
            git push